(ns club.bhikers.lib.config
  (:require ["package:latlong2/latlong.dart" :as ll]))

;; =============================================================================
;; CONSTANTS & DEFAULTS
;; =============================================================================

(defonce default-latest-release-api "https://api.github.com/repos/parasitid/bhikers.club/releases/latest")
(defonce supported-locales ["en" "fr" "it" "es" "de" "ru"])
(defonce default-locale "en")
(defonce max-pois-radius 10000) ;; 20km
(defonce min-pois-radius 500)   ;; 500m

(defonce supported-poi-types ["shelter"
                              "hotel"
                              "campsite"
                              "restaurant"
                              "sandwich"
                              "bikeshop"
                              "bottlerefill"
                              "toilet"])

(defonce default-poi-type "sandwich")

;; =============================================================================
;; MAP CONFIGURATION
;; =============================================================================

(defonce raster-tile-servers
  {"osm" {:name "OpenStreetMap"
          :url "https://tile.openstreetmap.org/{z}/{x}/{y}.png"}
   "otm" {:name "OpenTopoMap"
          :url "https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png"}
   "cyclosm" {:name "CyclOSM"
              :url "https://{s}.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png"}})

(defonce vector-tile-styles
  {"protomaps" {:name "MapLibre (Protomaps)"
                :url "https://api.protomaps.com/styles/v2/light.json?key=48c711a2fc69c6f0"}})

(defonce icicommencelaventure (ll/LatLng 48.51479 2.65053))
(defonce vertouplage (ll/LatLng 47.1612 -1.4778))

;; =============================================================================
;; FEATURE FLAGS
;; =============================================================================

(defonce feat-fall-detector? false)
(defonce feat-enhance-gpx? false)
