(ns club.bhikers.lib.pois
(:require
["package:latlong2/latlong.dart" :refer [LatLng]]
[club.bhikers.lib.config :refer [poi-types->osm-tags]]
[club.bhikers.lib.logging :as logging]
[club.bhikers.lib.overpassapi :as oapi]))

(defn poi-type->osm-tags [type] (get poi-types->osm-tags type false))

(defn overpass-item->poi
"Converts an Overpass API item to a POI map.
Injects lat/lon for 'way' items by finding their first node."
[^Map item items selected-poi-type]
(.putIfAbsent item "poi-type" (fn [] selected-poi-type))
(when (= (get item "type") "way")
;; finds way's first node id into items to inject lat/lon into item
(when-let [first-way-node (some #(let [first-node-id (first (get item "nodes" []))]
(when (and (not= nil first-node-id)
(= first-node-id (get % "id")))
%))
items)]
(doto item
(.putIfAbsent "lat" (fn [] (get first-way-node "lat")))
(.putIfAbsent "lon" (fn [] (get first-way-node "lon"))))))
item)

(defn fetch-pois-by-type
"Fetches POIs of a specific OSM type (node/way) for given tags.
Returns a list of POI maps."
[overpass-api t lat lon tags radius selected-poi-type]
(let [all-items (await (oapi/query overpass-api t lat lon tags radius))]
(if (nil? all-items)
nil
(let [typed-items (filter #(= t (get % "type")) all-items)]
(map #(overpass-item->poi % all-items selected-poi-type) typed-items)))))

(defn dynamic-map-pois
"Creates a reactive POI atom that updates based on map state changes.
It manages API queries and updates the 'pois' atom accordingly."
[map-state overpass-api]
(let [pois (atom [])
query-reporter (atom "")]
(add-watch query-reporter :report-map-msg (fn [_ _ _ new-msg] (swap! map-state assoc :message new-msg)))
(add-watch map-state :refresh-pois
(fn [_ _ old-state new-state]
(when (not= (select-keys old-state [:radius :selected-poi-type :current-pos :current-center :current-pos-as-center?])
(select-keys new-state [:radius :selected-poi-type :current-pos :current-center :current-pos-as-center?]))
(logging/d "refreshing pois!")
(let [{:keys [radius selected-poi-type current-pos current-center current-pos-as-center?]} new-state
[lat lon] (if (and current-pos-as-center? current-pos) current-pos current-center)
osm-tags (poi-type->osm-tags selected-poi-type)]
(when (or (and current-pos-as-center? current-pos) current-center)
(reset! pois [])
(doseq [t ["node" "way"]
tags (partition-all 2 osm-tags)]
(reset! query-reporter (str "fetch:" t tags))
(let [_pois (await (fetch-pois-by-type overpass-api t lat lon tags radius selected-poi-type))]
(cond
(nil? _pois)
(reset! query-reporter (str "FAILED! " t tags))
(empty? _pois)
(logging/d "no pois fetched! map-state was: " new-state)
:else
(do (logging/d "adding " (count _pois) " pois fetched!")
(swap! pois into _pois)))))
(reset! query-reporter (str "fetched " (count @pois) " pois.")))))))

pois))

(defn poi->LatLng [poi] (LatLng (get poi "lat") (get poi "lon")))
