(ns club.bhikers.screens.common-test
  (:require ["package:flutter_test/flutter_test.dart" :as ft]
            ["package:flutter/material.dart" :as m]
            [club.bhikers.main :refer [BhikersClubApp]]
            [club.bhikers.lib.state :as state]
            [club.bhikers.test-utils :as tu]
            [cljd.test :as t :refer [deftest]]))

(deftest about-version-test
  :tags [:widget]
  :runner (ft/testWidgets [tester])
  (let [^ft/WidgetTester {:flds [pumpWidget pumpAndSettle firstState tap]} tester]
    (await (tu/init-test-env!))
    (await (pumpWidget (BhikersClubApp "/settings")))
    (await (pumpAndSettle))
    ;; Open drawer
    (let [^m/ScaffoldState scaffold-state (#/(firstState m/ScaffoldState)
                                          (ft/find.byType m/Scaffold))]
      (.openDrawer scaffold-state)
      (await (pumpAndSettle)))
    ;; Tap AboutListTile
    (await (tap (ft/find.byType m/AboutListTile)))
    (await (pumpAndSettle))
    (ft/expect (ft/find.text (get @state/app-info :app-name)) ft/findsOneWidget)))
