(ns club.bhikers.screens.settings.ui
  (:require ["package:flutter/material.dart" :as m]
            ["package:flutter_settings_screens/flutter_settings_screens.dart" :as settings]
            ["package:easy_localization/easy_localization.dart" :as l10n]
            [club.bhikers.lib.i18n :refer [l10n-str]]
            [club.bhikers.lib.utils :refer [str->int
                                            str->location-accuracy
                                            location-accuracy->str]]
            [club.bhikers.lib.logging :as logging]
            [club.bhikers.lib.state :refer [selected-poi-type
                                            force-debug-mode?
                                            pois-radius
                                            api-query-timeout
                                            refresh-location-distance-filter
                                            refresh-location-interval-duration
                                            refresh-location-accuracy]]
            [club.bhikers.lib.config :refer [supported-poi-types
                                          supported-locales default-locale
                                          max-pois-radius
                                          min-pois-radius]]
            [cljd.flutter :as f]))

;; =============================================================================
;; General Settings
;; =============================================================================

(defn general-group [ctx]
  (settings/SettingsGroup
   .title  (l10n-str "settings.general_group_title")
   .children
   [(settings/SliderSettingsTile
     .leading (m/Icon m/Icons.adjust)
     .settingKey "/general/pois-radius"
     .title (l10n-str "common.radius")
     .defaultValue 1000
     .min min-pois-radius
     .max max-pois-radius
     .onChange #(reset! pois-radius %)
     .step 500)
    (#/(settings/DropDownSettingsTile String)
     .leading (m/Icon m/Icons.location_searching)
     .settingKey "/general/default-poi-type"
     .title  (l10n-str "settings.default_poi_type")
     .values (into {} (map (fn [poi] [poi (l10n-str (str "around_me.pois." poi))])
                           supported-poi-types))
     .selected @selected-poi-type
     .onChange #(reset! selected-poi-type %))
    (#/(settings/DropDownSettingsTile String)
     .leading (m/Icon m/Icons.language)
     .settingKey "/general/language"
     .title  (l10n-str "settings.language")
     .values (into {} (map (fn [lang] [lang (l10n-str (str "settings.langs." lang))])
                           supported-locales))
     .selected default-locale
     .onChange (fn [lang]
                 (logging/d "Changing language to: " lang)
                 (try
                   (-> ctx
                       l10n/BuildContextEasyLocalizationExtension
                       (.setLocale (m/Locale lang)))
                   (catch Exception e
                     (logging/e "Failed to change language: " e)))
                 nil))]))


;; =============================================================================
;; Location Settings
;; =============================================================================

(defn advanced-location-group []
  (settings/SettingsGroup
   .title  (l10n-str "settings.advanced_location_title")
   .children
   [(settings/TextInputSettingsTile
     .settingKey "/advanced-location/refresh-location-distance-filter"
     .title (l10n-str "settings.location_distance_filter")
     .keyboardType m/TextInputType.number
     .onChange #(let [distance (str->int % 0 10000)]
                  (when distance (reset! refresh-location-distance-filter distance)))
     .validator #(when (not (str->int % 0 10000))
                   (l10n-str "settings.distance_filter_input_validation_error"))
     .initialValue (str @refresh-location-distance-filter))
    (#/(settings/DropDownSettingsTile String)
     .leading (m/Icon m/Icons.location_searching)
     .settingKey "/advanced-location/refresh-location-accuracy"
     .title  (l10n-str "settings.refresh_location_accuracy")
     .values {"low" (l10n-str "settings.location_accuracy_low")
              "medium" (l10n-str "settings.location_accuracy_medium")
              "high" (l10n-str "settings.location_accuracy_high")}
     .selected (location-accuracy->str @refresh-location-accuracy)
     .onChange #(reset! refresh-location-accuracy (str->location-accuracy %)))
    (#/(settings/DropDownSettingsTile int)
     .leading (m/Icon m/Icons.location_searching)
     .settingKey "/advanced-location/refresh-location-interval-duration"
     .title  (l10n-str "settings.refresh_location_interval_duration")
     .values {5 "5s"
              30 "30s"
              60 "1m"
              (* 5 60) "5m"
              (* 10 60) "10m"
              (* 30 60) "30m"
              (* 60 60) "1h"}
     .selected (.-inSeconds ^Duration @refresh-location-interval-duration)
     .onChange #(reset! refresh-location-interval-duration (Duration .seconds %)))]))

;; =============================================================================
;; Advanced Settings
;; =============================================================================

(defn advanced-group []
  (settings/SettingsGroup
   .title  (l10n-str "settings.advanced_group_title")
   .children
   [(settings/TextInputSettingsTile
     .settingKey "/advanced/api-query-timeout"
     .title (l10n-str "settings.api_query_timeout")
     .keyboardType m/TextInputType.number
     .onChange #(let [timeout (str->int % 2 10)]
                  (when timeout (reset! api-query-timeout timeout)))
     .validator #(when (not (str->int % 2 10))
                   (l10n-str "settings.timeout_input_validation_error"))
     .initialValue (str @api-query-timeout))
    (settings/SwitchSettingsTile
     .leading (m/Icon m/Icons.bug_report)
     .settingKey "/advanced/debug-mode?"
     .title (l10n-str "settings.debug_mode")
     .onChange #(reset! force-debug-mode? %))]))