(ns club.bhikers.lib.pois.ui
(:require
[clojure.string :refer [replace]]
["package:flutter/material.dart" :as m]
["package:url_launcher/url_launcher.dart" :refer [canLaunchUrl launchUrl LaunchMode]]
["package:maps_launcher/maps_launcher.dart" :refer [MapsLauncher]]
["package:url_launcher/link.dart" :as link]
[cljd.flutter :as f]
[club.bhikers.lib.config :refer [osm-tags->icons]]
[club.bhikers.lib.i18n :refer [l10n-str]]))


(defn osm-tag->icon [[type value]]
(get osm-tags->icons (str type "=" value)))

(defn poi->map-location-marker [poi]
(let [osm-tags-icons (filter some? (map osm-tag->icon (get poi "tags")))]
;; theres always at least one matching icon for poi tags. otherwise its a bug.
(first osm-tags-icons)))

;; =============================================================================
;; Actions
;; =============================================================================

(defn route-to-poi [poi]
(-> MapsLauncher (.launchCoordinates (get poi "lat") (get poi "lon"))))

(defn edit-poi [poi]
(let [geoedit-uri (Uri.parse (str "geo:" (get poi "lat") "," (get poi "lon")))]
(if (await (canLaunchUrl (Uri.parse "everydoor://")))
(await (launchUrl geoedit-uri))
(await (launchUrl (Uri.parse "https://every-door.app/")
.mode LaunchMode.externalApplication)))))

;; =============================================================================
;; POI Details Widgets
;; =============================================================================

(defonce priority-list ["name" "phone" "contact:phone" "website" "email"])

(defn basic-converter [scheme icon]
(fn [value]
(f/widget
(link/Link .uri (Uri.parse (str scheme value))
.target link/LinkTarget.blank
.builder (f/build [open-link]
(f/widget
(m/TextButton.icon .onPressed open-link
.label (m/Text value .overflow m/TextOverflow.fade .softWrap true .maxLines 2)
.icon (m/Icon icon))))))))

(defonce phone-converter (basic-converter "tel://" m/Icons.call))
(defonce email-converter (basic-converter "mailto://" m/Icons.email))
(defonce website-converter (basic-converter "" m/Icons.open_in_browser))

(defonce converters {"phone" phone-converter
"mobile" phone-converter
"contact:phone" phone-converter
"contact:mobile" phone-converter
"contact:email" email-converter
"contact:website" website-converter
"contact:facebook" website-converter
"contact:instagram" website-converter
"email" email-converter
"website" website-converter})

(defn osm-tag-value->widget [type value]
(if-let [converter (get converters type)]
(converter value) ;; Apply conversion if a function exists
(m/Text value .overflow m/TextOverflow.ellipsis .softWrap true .maxLines 2)))

(defn osm-tag-key->widget [type]
(m/Text (replace type #"[:_]" " ")
.style (m/TextStyle .fontWeight m/FontWeight.bold)
.overflow m/TextOverflow.fade .softWrap true .maxLines 2))

(defn prioritized-attrs [tags]
(let [widgets (into {} tags)
prioritized-widgets (filter some? (map (fn [key] (when-let [value (get widgets key)] [key value]))
priority-list))
other-widgets (into {} (filter #(not ((set priority-list) (key %))) widgets))]
(concat prioritized-widgets other-widgets)))

(defn poi->attributes-listview [poi]
(m/ListView
.children (map (fn [[type value]]
(m/Row .mainAxisAlignment m/MainAxisAlignment.start
.children [(f/widget (m/Expanded .flex 3) (osm-tag-key->widget type))
(f/widget (m/Expanded .flex 5) (osm-tag-value->widget type value))
(or (osm-tag->icon [type value]) (m/Container))]))
(prioritized-attrs (get poi "tags" {})))))

(defn poi->title-widget [poi]
(let [poi-name (get-in poi ["tags" "name"] (l10n-str "common.no_name"))
osm-tags-icons (filter some? (map osm-tag->icon (get poi "tags")))]
(f/widget
(m/Expanded .flex 2)
(m/Row .children (concat
osm-tags-icons
[(m/Text poi-name
.overflow m/TextOverflow.fade
.style (m/TextStyle .fontSize 16 .fontWeight m/FontWeight.bold))])))))
